"""Planning and verifying the public surface.

Two halves of one boundary:

`plan_publication` walks `events/`, asks the distribution policy about every
file, and produces an allowlist. Its bias is deliberate: it enumerates what is
*on disk*, not what the manifests promise, so a file nobody recorded is denied
rather than overlooked.

`verify_site` checks an assembled site tree against that allowlist by set
difference. Nothing here recognises "dangerous" files — a pattern match would
be a blocklist, permanently one artifact behind. An unrecognised file under an
`events/` tree is a violation because it was not authorised, and that is the
only property worth enforcing.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from geosteward.harness.distribution import ArtifactRef, DistributionPolicy

#: Absolute paths that identify a machine and its user. Manifest `inputs` name
#: the maintainer's workstation, which is honest provenance inside a private
#: repository and needless disclosure on a public site — the sha256 is the
#: verifiable anchor, the absolute path adds nothing reproducible.
WORKSTATION_PATH = re.compile(
    r"(?:[A-Za-z]:[\\/]Users[\\/][^\\/\"]+|/Users/[^/\"]+|/home/[^/\"]+)"
)

REDACTED_PREFIX = "<workstation>"

#: Accountability records live beside the artifacts rather than inside the
#: manifest, so they are classified by filename.
META_KINDS = {
    "artifact_manifest.jsonl": "artifact_manifest",
    "audit_log.jsonl": "audit_log",
}

#: Only the manifest carries workstation paths, but the flag is derived from
#: the kind rather than hardcoded per file so a new record type inherits it.
REDACTED_KINDS = {"artifact_manifest"}


@dataclass(frozen=True)
class PlannedFile:
    path: str
    kind: str
    rule_id: str
    redact_workstation_paths: bool


@dataclass(frozen=True)
class DeniedFile:
    path: str
    kind: str
    rule_id: str
    reason: str


@dataclass
class PublicationPlan:
    allowed: list[PlannedFile] = field(default_factory=list)
    denied: list[DeniedFile] = field(default_factory=list)

    def to_json(self) -> str:
        return json.dumps(
            {
                "schema_version": "geosteward-publication-allowlist-v1",
                "note": (
                    "Generated by scripts/publication_boundary.py from the distribution "
                    "plane in policy_v1.yaml. Do not hand-edit: CI regenerates this and "
                    "fails if it differs."
                ),
                "allowed": [
                    {
                        "path": f.path,
                        "kind": f.kind,
                        "rule_id": f.rule_id,
                        "redact_workstation_paths": f.redact_workstation_paths,
                    }
                    for f in self.allowed
                ],
                "denied": [
                    {"path": d.path, "kind": d.kind, "rule_id": d.rule_id, "reason": d.reason}
                    for d in self.denied
                ],
            },
            indent=2,
            ensure_ascii=False,
        )
        # trailing newline is added by write_allowlist


@dataclass(frozen=True)
class Violation:
    kind: str
    path: str
    detail: str


#: Sort key for anything whose order reaches a committed file.
#:
#: `sorted()` over `Path` objects compares platform-dependently: `PurePath`
#: ordering is case-folded on Windows and case-sensitive on POSIX, so
#: `EATON_wildfire_..._profile.json` and `Eaton_Fire_profile.json` swap places
#: between the maintainer's workstation and CI. The allowlist is generated and
#: CI diffs it against a regeneration, so that turns a cosmetic difference into
#: a failing build for whoever regenerates on the other platform. Ordering by
#: the POSIX string makes the artifact a function of the policy alone.
def _sort_key(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _kinds_by_path(events_root: Path) -> dict[str, str]:
    """Artifact path -> kind, from every committed manifest."""
    kinds: dict[str, str] = {}
    manifests = sorted(
        events_root.glob("*/artifact_manifest.jsonl"),
        key=lambda p: _sort_key(p, events_root),
    )
    for manifest in manifests:
        for line in manifest.read_text(encoding="utf-8").splitlines():
            if line.strip():
                row = json.loads(line)
                kinds[row["path"]] = row["kind"]
    return kinds


def plan_publication(
    events_root: Path,
    policy: DistributionPolicy,
    published_events: list[str] | None = None,
) -> PublicationPlan:
    """Classify every file under `events/` for publication.

    `published_events` scopes the walk to the events that form the current
    public surface. It is a governance decision, so it comes from the policy
    file rather than a build script — a retired event keeps its artifacts and
    its provenance on disk while leaving the site.
    """
    scope = policy.published_events if published_events is None else published_events
    kinds = _kinds_by_path(events_root)
    plan = PublicationPlan()
    repo_root = events_root.parent
    roots = [events_root / event for event in scope]
    files = [p for root in roots for p in root.rglob("*") if p.is_file()]
    for path in sorted(files, key=lambda p: _sort_key(p, repo_root)):
        rel = path.relative_to(repo_root).as_posix()
        kind = META_KINDS.get(path.name) or kinds.get(rel)
        if kind is None:
            plan.denied.append(
                DeniedFile(
                    path=rel,
                    kind="unrecorded",
                    rule_id="default-deny-unrecorded",
                    reason=(
                        "File is present on disk but absent from any artifact manifest; "
                        "it has no provenance and is not authorised for publication."
                    ),
                )
            )
            continue
        decision = policy.evaluate(ArtifactRef(path=rel, kind=kind))
        if decision.allowed:
            plan.allowed.append(
                PlannedFile(
                    path=rel,
                    kind=kind,
                    rule_id=decision.rule_id,
                    redact_workstation_paths=kind in REDACTED_KINDS,
                )
            )
        else:
            plan.denied.append(
                DeniedFile(
                    path=rel, kind=kind, rule_id=decision.rule_id, reason=decision.reason
                )
            )
    return plan


def write_allowlist(plan: PublicationPlan, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(plan.to_json() + "\n", encoding="utf-8")


def redact(text: str) -> str:
    return WORKSTATION_PATH.sub(REDACTED_PREFIX, text)


def verify_site(site_dir: Path, allowlist: list[str]) -> list[Violation]:
    """Violations in an assembled site tree; empty list means it may deploy."""
    allowed = set(allowlist)
    violations: list[Violation] = []
    files = [p for p in site_dir.rglob("*") if p.is_file()]
    for path in sorted(files, key=lambda p: _sort_key(p, site_dir)):
        rel = path.relative_to(site_dir).as_posix()
        # A site places the events tree under a deploy prefix (e.g. app/).
        # Normalise to the repository-relative form the allowlist speaks.
        if "events/" not in rel:
            continue
        artifact_rel = "events/" + rel.split("events/", 1)[1]
        if artifact_rel not in allowed:
            violations.append(
                Violation(
                    kind="unauthorized_artifact",
                    path=rel,
                    detail=(
                        f"{artifact_rel} is present in the site tree but not on the "
                        "publication allowlist."
                    ),
                )
            )
            continue
        leaked = _leaked_paths(path)
        if leaked:
            violations.append(
                Violation(
                    kind="leaked_workstation_path",
                    path=rel,
                    detail=f"{artifact_rel} discloses workstation paths: {sorted(leaked)[:3]}",
                )
            )
    return violations


def _leaked_paths(path: Path) -> set[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, ValueError):
        return set()  # binary product; paths are not embedded in geometry
    return set(WORKSTATION_PATH.findall(text))
